print("london is the world ")
print("south africa")
print("egypt")
print("nigeria")
print("morocco")
print("united states")
print("argentina")
print("cuba")
print("mexico")
print("cannada")
#Asia
print("china")
print("japan")
print("korea")
print("thailand")
print("saudi")
print("iran")
#europe
print("uk")
print("germany")
print("france")
print("Russia")
print("swiss")

